from functools import partial
from typing import Optional, Sequence

from result import Result

type WithErrors[A] = Result[Sequence[str], A]


class A1: ...


class A2: ...


class A3: ...


class B1: ...


class B2: ...


class C1: ...


class C2: ...


class C3: ...


class C4: ...


class D1: ...


class D2: ...


class E: ...


class F: ...


init1 = A1()
init2 = A2()
init3 = A3()


def step1_1(a: A1) -> Optional[B1]: ...
def step1_2(a: A2, b: B1) -> WithErrors[B2]: ...
def step2_1(a: A1) -> WithErrors[C1]: ...
def step2_2_throws(c: C1) -> C2: ...
def step2_3(c: C1) -> WithErrors[C3]: ...
def step2_4(c1: C1, c2: C2, c3: C3) -> C4: ...
def step3_1(a: A1) -> Sequence[D1]: ...
def step3_2(c: D1) -> WithErrors[D2]: ...
def step4(b: B2, c: C4, d: Sequence[D2]) -> E: ...
def step5(a: A3, e: E) -> F: ...

def missing_error() -> Sequence[str]: ...
def error_handler(e) -> Sequence[str]: ...

optional = Result.optional
safe = Result.safe
traverse = Result.traverse
combine3 = Result.combine3

# sub1 = Result.optional(step1_1(init1), missing_error).flat_map(lambda b: step1_2(init2, b))
sub1 = Result.optional(step1_1(init1), missing_error).flat_map(partial(step1_2, init2))
sub2: WithErrors[C4] = step2_1(init1).
sub3 = traverse(step3_1(init1), step3_2)

combine3(sub1, sub2, sub3).using(step4).map(partial(step5, init3))


